Update codecov.yaml with github path for report

diff --git a/.github/workflows/codecov.yaml b/.github/workflows/codecov.yaml
--- a/.github/workflows/codecov.yaml
+++ b/.github/workflows/codecov.yaml
@@ -45,17 +45,25 @@ jobs:
     - name: Install dependencies for covr and testthat
       run: R -e 'install.packages(c("covr", "testthat"), dependencies = TRUE)'
 
-
     - name: Run tests and calculate coverage
       run: |
         echo "Current working directory: $(pwd)"
         R -e 'library(covr); covr::package_coverage()'
 
+    - name: Check if coverage report exists
+      run: |
+        if [ -f "${{ github.workspace }}/coverage.xml" ]; then
+          echo "Coverage report found."
+        else
+          echo "Coverage report not found."
+          exit 1  # Exit with an error if the report is missing
+        fi
+
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v3
       with:
         token: ${{ secrets.CODECOV_TOKEN }}
-        coverage_reports: "/home/runner/work/NRTAPmodel/NRTAPmodel/coverage.xml"
+        coverage_reports: ${{ github.workspace }}/coverage.xml
         
     - name: Cleanup
       run: |
